- name: Create www group
  group: name=www state=present

- name: Create www user
  user: name=www comment="WWW user" group=www home={{ logical_volumes.home2.mount_point }}/www

- name: Create www dir
  file: path=/www owner=www group=www state=directory

- name: Install git
  action: apt pkg=git state=latest install_recommends=yes

- name: Git update valtionavustus
  sudo: yes
  sudo_user: www
  git: repo=https://github.com/Opetushallitus/valtionavustus.git dest=/www/valtionavustus

- name: Create logs dir
  file: path={{ logical_volumes.logs.mount_point }}/valtionavustus owner=www group=www state=directory

- name: Migrate db
  sudo: yes
  sudo_user: www
  shell: ./lein with-profile {{ app_profile }} dbmigrate >> {{ logical_volumes.logs.mount_point }}/valtionavustus/lein_dbmigrate.log 2>&1
  args:
      chdir: /www/valtionavustus

- name: Start valtionavustus server
  sudo: yes
  sudo_user: www
  shell: nohup ./lein with-profile {{ app_profile }} run >> {{ logical_volumes.logs.mount_point }}/valtionavustus/lein_run.log 2>&1 &
  args:
      chdir: /www/valtionavustus

- name: Wait server to start
  wait_for: port=8081 delay=1 timeout=60
