- name: Create www group
  group: name=www state=present

- name: Create www user
  user: name=www comment="WWW user" group=www home={{ logical_volumes.home2.mount_point }}/www

- name: Create va-deploy user
  user: name=va-deploy comment="User for application deploys" group=www-data

- name: Create www dir
  file: path=/www owner=www group=www state=directory

- name: Install git
  action: apt pkg=git state=latest install_recommends=yes

- name: Git update valtionavustus
  sudo: yes
  sudo_user: www
  git: repo=https://github.com/Opetushallitus/valtionavustus.git dest=/www/valtionavustus

- name: Create logs dir
  file: path={{ logical_volumes.logs.mount_point }}/valtionavustus owner=www group=www state=directory

- name: Add script to stop the application
  template: src=stop_app.bash.j2 dest=/usr/local/bin/stop_app.bash owner=root group=root mode=0755

- name: Add script to run the application
  template: src=run_app.bash.j2 dest=/usr/local/bin/run_app.bash owner=root group=root mode=0755

- name: Allow va-deploy to stop the application
  lineinfile: 'dest=/etc/sudoers line="va-deploy ALL=(ALL) NOPASSWD: /usr/local/bin/stop_app.bash" validate="visudo -cf %s"'

- name: Allow va-deploy to start the application
  lineinfile: 'dest=/etc/sudoers line="va-deploy ALL=(ALL) NOPASSWD: /usr/local/bin/run_app.bash" validate="visudo -cf %s"'

- name: Add script to run arbitrary SQL file to our db
  template: src=run_sql.bash.j2 dest=/usr/local/bin/run_sql.bash owner=postgres group=postgres mode=0700

- name: Allow va-deploy to run SQL scripts
  lineinfile: 'dest=/etc/sudoers line="va-deploy ALL=(postgres) NOPASSWD: /usr/local/bin/run_sql.bash" validate="visudo -cf %s"'