- name: Create a virtual machine {{ machine_name }} ({{ va_floating_ip }})
  nova_compute:
    state: present
    name: "{{ machine_name }}"
    login_username: "{{ pouta_username }}"
    login_password: "{{ pouta_password }}"
    login_tenant_name: "{{ tenant_name }}"
    auth_url: "{{ auth_url }}"
    image_id: "{{ pouta_ubuntu_14_04 }}"
    key_name: "{{ pouta_key }}"
    flavor_id: "{{ pouta_tiny }}"
    security_groups: "{{ va_security_groups }}"
    nics:
      - net-id: "{{ va_network }}"
    floating_ips:
      - "{{ va_floating_ip }}"
