- name: Create a virtual machine {{ machine_name }} (without floating IP) for groups {{ va_ansible_host_groups }}
  nova_compute:
    state: present
    name: "{{ machine_name }}"
    login_username: "{{ pouta_username }}"
    login_password: "{{ pouta_password }}"
    login_tenant_name: "{{ tenant_name }}"
    auth_url: "{{ auth_url }}"
    image_name: "{{ pouta_ubuntu_14_04 }}"
    key_name: "{{ pouta_key }}"
    flavor_id: "{{ pouta_flavor_id }}"
    security_groups: "{{ va_security_groups }}"
    nics:
      - net-id: "{{ va_network }}"
    meta:
      ansible_host_groups: "{{ va_ansible_host_groups }}"

- name: Remove the old SSH host key of {{ machine_name }} from my ~/.ssh/known_hosts
  shell: "ssh-keygen -R {{ machine_name }}"