- name: Create a virtual machine {{ machine_name }} ({{ va_floating_ip }})
  nova_compute:
    state: present
    name: "{{ machine_name }}"
    login_username: "{{ pouta_username }}"
    login_password: "{{ pouta_password }}"
    login_tenant_name: "{{ tenant_name }}"
    auth_url: "{{ auth_url }}"
    image_id: "{{ pouta_ubuntu_14_04 }}"
    key_name: "{{ pouta_key }}"
    flavor_id: "{{ pouta_tiny }}"
    security_groups: "{{ va_security_groups }}"
    nics:
      - net-id: "{{ va_network }}"
    floating_ips:
      - "{{ va_floating_ip }}"

- name: Wait for  {{ machine_name }} ({{ va_floating_ip }}) to start
  local_action:
    module: wait_for
      host={{ va_floating_ip }}
      port=22
      delay=1
      timeout=300

- name: Add our public keys to nova keys
  nova_keypair: state=present login_username="{{ pouta_username }}"
                login_password="{{ pouta_password }}"
                login_tenant_name="{{ tenant_name }}" name=ansible_key-"{{ item | basename }}"
                public_key="{{ lookup('file', item) }}"
  with_fileglob:
    - ../roles/common/files/public_keys/*

- name: Remove the old SSH host key of {{ va_floating_ip }} from my ~/.ssh/known_hosts
  shell: "ssh-keygen -R {{va_floating_ip}}"

- name: Add the new SSH host key of {{ va_floating_ip }} to my ~/.ssh/known_hosts
  shell: "ssh-keyscan -H  {{va_floating_ip}} >> ~/.ssh/known_hosts"

- name: Copy our public keys to {{ machine_name }} ({{ va_floating_ip }}) ~cloud-user/.ssh/authorized_keys
  shell: cat ./roles/common/files/public_keys/* | ssh -i ~/.ssh/pouta-`whoami`.pem cloud-user@{{ va_floating_ip }} 'cat >>  ~cloud-user/.ssh/authorized_keys'