- name: Debug hostvars
  debug: var=hostvars

- name: Add Oracle Java APT repository to sources
  action: apt_repository repo='ppa:webupd8team/java'
  when: ansible_os_family == 'Debian'

- name: Update APT package cache
  apt: update_cache=yes cache_valid_time=3600
  when: ansible_os_family == 'Debian'

- name: Upgrade APT packages
  apt: upgrade=safe
  when: ansible_os_family == 'Debian'

- name: Run YUM security updates
  command: yum --security update
  register: yum_security_updates
  when: ansible_os_family == 'RedHat'
- debug: var=yum_security_updates.stdout_lines
  when: ansible_os_family == 'RedHat'

- name: Install required APT packages
  apt: state=installed pkg={{ item }}
  with_items: ubuntu_common_required_packages
  when: ansible_os_family == 'Debian'

- name: Install required YUM packages
  yum: state=installed pkg={{ item }}
  with_items: centos_common_required_packages
  when: ansible_os_family == 'RedHat'

- name: Disable RepeatedMsgReduction of rsyslogd because it is buggy
  lineinfile: dest=/etc/rsyslog.conf regexp="^\$RepeatedMsgReduction" line="$RepeatedMsgReduction off" backup=yes
  register: rsyslog_config

- name: Restart rsyslog if config was changed
  service: name=rsyslog state=restarted
  when: rsyslog_config.changed

- name: APT Install rng-tools to avoid /dev/random exhaust
  apt: name=rng-tools
  when: ansible_os_family == 'Debian'

- name: YUM Install rng-tools to avoid /dev/random exhaust
  yum: name=rng-tools
  when: ansible_os_family == 'RedHat'

- lineinfile: dest=/etc/default/rng-tools line="HRNGDEVICE=/dev/urandom"
  when: ansible_os_family == 'Debian'

- name: Add systemd override directory for rngd
  file: path=/etc/systemd/system/rngd.service.d state=directory owner=root mode=0755
  when: ansible_os_family == 'RedHat'
  tags: rngd

- name: Add systemd override for rngd to use /dev/urandom device as input
  copy:
    src: rngd-systemctl-override.conf
    dest: /etc/systemd/system/rngd.service.d/override.conf
    owner: root
    mode: 0644
  register: rngd_service_changed
  when: ansible_os_family == 'RedHat'

- name: reload systemd if rngd was changed
  command: systemctl daemon-reload
  when: rngd_service_changed.changed

- name: restart rngd if its config was changed
  service: name=rngd state=restarted
  when: rngd_service_changed.changed

- name: Force rng-tools restart and run it on boot
  service: name=rng-tools state=restarted enabled=yes
  when: ansible_os_family == 'Debian'

- name: Force rng daemon restart and run it on boot
  service: name=rngd state=restarted enabled=yes
  when: ansible_os_family == 'RedHat'

- name: Gather production application server names to list
  debug:
    msg: |
          {% set comma = joiner(",") %}
          {% for server in groups['va_app_prod'] -%}
              {{ comma() }}{{ server }}
          {%- endfor %}
  register: production_application_server_names
  when: "'va_app_prod' in groups"

- name: Disable selinux
  selinux: state=disabled
