- name: Get cert list
  local_action: command find {{certs_dir}} -print -mindepth 1 -maxdepth 1 -name '*-vault.pem'
  sudo: no
  register: cert_files
  check_mode: no

- name: Remove certificates from the server
  file:
    path: "/etc/pki/domain/certs/{{item | basename | regex_replace('-vault')}}"
    state: absent
  with_items: "{{ cert_files.stdout_lines }}"
  notify: Restart haproxy
