version: 0.0
os: linux
files:
  - source: va-virkailija/target/uberjar/virkailija-0.1.0-SNAPSHOT-standalone.jar
    destination: /home/ec2-user/va-virkailija/
hooks:
  ApplicationStart:
    - location: ci/dev_start_virkailija.sh
      timeout: 10
      runas: ec2-user
