version: '3.3'

services:
  virkailija:
    image: va-virkailija:latest
    container_name: va-virkailija
    hostname: va-virkailija
    environment:
      JAVA_TOOL_OPTIONS: '-Duser.timezone="Europe/Helsinki"'
    volumes:
      - /dev/urandom:/dev/random
    ports:
      - '8081:8081'
    depends_on:
      - hakija
      - fakesmtp
      - maksatuspalvelu
    networks:
      - subnet-private
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8081/api/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5

  hakija:
    image: va-hakija:latest
    container_name: va-hakija
    hostname: va-hakija
    environment:
      JAVA_TOOL_OPTIONS: '-Duser.timezone="Europe/Helsinki"'
    volumes:
      - /dev/urandom:/dev/random
    ports:
      - '8080:8080'
    depends_on:
      - db
      - fakesmtp
    networks:
      - subnet-private
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8080/api/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:12.2
    volumes:
      - ./scripts/postgres-docker/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: va-postgres
    hostname: va-postgres
    ports:
      - '5432:5432'
    networks:
      - subnet-private
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_USER: 'va'
      POSTGRES_PASSWORD: 'va'
      PGDATA: '/tmp/'
      TZ: "Europe/Helsinki"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  fakesmtp:
    image: rcs-fakesmtp
    container_name: rcs-fakesmtp
    hostname: fakesmtp
    networks:
      - subnet-private

  maksatuspalvelu:
    image: atmoz/sftp
    hostname: maksatuspalvelu
    volumes:
      - ./maksatuspalvelu/initialize-maksatuspalvelu.sh:/etc/sftp.d/initialize-maksatuspalvelu.sh
      - ./maksatuspalvelu/identity/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
      - ./maksatuspalvelu/identity/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
    ports:
      - '42022:22'
    command: demo:pass:1001:100
    networks:
      - subnet-private

networks:
  subnet-private:
