version: '3.9'

services:
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.playwright-test-runner
    container_name: va-playwright-tests
    depends_on:
      va:
        condition: service_healthy
    volumes:
      - ./playwright-results:/playwright-results
    environment:
      HEADLESS: 'true'
      VIRKAILIJA_HOSTNAME: va
      HAKIJA_HOSTNAME: va
      PLAYWRIGHT_WORKERS: "${PLAYWRIGHT_WORKERS:-5}"
      PLAYWRIGHT_RETRIES: 1
      PLAYWRIGHT_SHARD: "${PLAYWRIGHT_SHARD-}"
      PLAYWRIGHT_SHARDS_AMOUNT: "${PLAYWRIGHT_SHARDS_AMOUNT-}"
      TZ: 'Europe/Helsinki'
    logging:
      options:
        mode: 'non-blocking'

  va:
    build:
      context: .
      dockerfile: ./Dockerfile.hakija
    hostname: va
    environment:
      JAVA_TOOL_OPTIONS: '-Duser.timezone="Europe/Helsinki"'
    volumes:
      - /dev/urandom:/dev/random
    depends_on:
      db:
        condition: service_healthy
      fakesmtp:
        condition: service_started
      maksatuspalvelu:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8081/api/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      options:
        mode: 'non-blocking'

  db:
    image: postgres:12.2
    volumes:
      - ./scripts/postgres-docker/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    hostname: va-postgres
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_USER: 'va'
      POSTGRES_PASSWORD: 'va'
      PGDATA: '/tmp/'
      TZ: "Europe/Helsinki"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      options:
        mode: 'non-blocking'

  db_restore-backup:
    extends: db
    volumes:
      - ./init-db-restore.sql:/docker-entrypoint-initdb.d/init.sql
      - va-postgres-pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'va'
      POSTGRES_PASSWORD: 'va'

  fakesmtp:
    build:
      context: .
      dockerfile: ./Dockerfile.rcs-fakesmtp
    hostname: fakesmtp
    volumes:
      - ./fakesmtp/mail:/var/mail
    logging:
      options:
        mode: 'non-blocking'

  maksatuspalvelu:
    image: atmoz/sftp
    hostname: maksatuspalvelu
    volumes:
      - ./maksatuspalvelu/initialize-maksatuspalvelu.sh:/etc/sftp.d/initialize-maksatuspalvelu.sh
      - ./maksatuspalvelu/identity/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
      - ./maksatuspalvelu/identity/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
    command: demo:pass:1001:100
    logging:
      options:
        mode: 'non-blocking'

volumes:
  va-postgres-pgdata:
