version: '3.3'

services:
  virkailijabackend:
    build:
      context: .
      dockerfile: ./Dockerfile.virkailija
    depends_on:
      - hakijabackend
    networks:
      - subnet-private

  hakijabackend:
    build:
      context: .
      dockerfile: ./Dockerfile.hakija
    depends_on:
      - db
    networks:
      - subnet-private

  db:
    image: postgres:9.4
    volumes:
      - ./scripts/postgres-docker/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: va-postgres
    hostname: va-postgres
    ports:
      - '5432:5432'
    networks:
      - subnet-private

networks:
  subnet-private:
