version: '3.3'

services:
  virkailija:
    image: va-virkailija:latest
    container_name: va-virkailija
    hostname: va-virkailija
    ports:
      - '8081:8081'
    depends_on:
      - hakija
    networks:
      - subnet-private

  hakija:
    image: va-hakija:latest
    container_name: va-hakija
    hostname: va-hakija
    ports:
      - '8080:8080'
    depends_on:
      - db
    networks:
      - subnet-private

  db:
    image: postgres:12.2
    volumes:
      - ./scripts/postgres-docker/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: va-postgres
    hostname: va-postgres
    ports:
      - '5432:5432'
    networks:
      - subnet-private
    environment:
      POSTGRES_USER: 'va'
      POSTGRES_PASSWORD: 'va'
      PGDATA: '/tmp/'

  fakesmtp:
    image: munkyboy/fakesmtp
    container_name: fakesmtp 
    volumes:
      - ./mail:/var/mail
    ports:
      - '42069:25'

networks:
  subnet-private:
