version: '3.9'

name: valtionavustus

services:
  va:
    extends:
      service: va-server
    command: with-profile server-dev run -m oph.va.hakija.main
    hostname: va
    depends_on:
      db:
        condition: service_healthy
      fakesmtp:
        condition: service_started
      maksatuspalvelu:
        condition: service_started
      pagerduty:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8081/api/healthcheck"]

  va-server:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - REVISION
    image: ${VA_SERVER_IMAGE-va-server:latest}
    pull_policy: missing
    volumes:
      - /dev/urandom:/dev/random
    environment:
      JAVA_TOOL_OPTIONS: '-Duser.timezone="Europe/Helsinki"'
      PAGERDUTY_API_ENDPOINT: 'http://pagerduty:8080/v2/enqueue'
      PAGERDUTY_ROUTING_KEY: '_not_used_on_local_dev_'
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 10
    logging:
      options:
        mode: 'non-blocking'


  db:
    image: postgres:12.2
    volumes:
      - ./scripts/postgres-docker/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    hostname: va-postgres
    command: ["postgres", "-c", "log_statement=all", "-c", "log_line_prefix='%m [%p] {%x} '"]
    environment:
      POSTGRES_USER: 'va'
      POSTGRES_PASSWORD: 'va'
      PGDATA: '/tmp/'
      TZ: "Europe/Helsinki"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      options:
        mode: 'non-blocking'


  fakesmtp:
    build:
      context: .
      dockerfile: ./Dockerfile.rcs-fakesmtp
    hostname: fakesmtp
    volumes:
      - ./fakesmtp/mail:/var/mail
    logging:
      options:
        mode: 'non-blocking'

  pagerduty:
    image: mendhak/http-https-echo:33
    hostname: pagerduty
    environment:
      ECHO_BACK_TO_CLIENT: false

  maksatuspalvelu:
    image: atmoz/sftp
    hostname: maksatuspalvelu
    volumes:
      - ./maksatuspalvelu/initialize-maksatuspalvelu.sh:/etc/sftp.d/initialize-maksatuspalvelu.sh
      - ./maksatuspalvelu/identity/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
      - ./maksatuspalvelu/identity/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
    command: demo:pass:1001:100
    logging:
      options:
        mode: 'non-blocking'
