name: valtionavustus-local
services:
  va:
    build:
      context: .
      args:
        - NODE_VERSION
    ports:
      - '127.0.0.1:8080:8080'
      - '127.0.0.1:8081:8081'
    volumes:
      - type: bind
        source: ./server/
        target: /app/server/
      - type: bind
        source: ./tmp/
        target: /tmp/
      - type: bind
        source: ./tmp/version.txt
        target: /app/server/resources/public/version.txt

  db:
    ports:
      - '127.0.0.1:42042:5432'

  fakesmtp:
    ports:
      - '127.0.0.1:42069:25'

  pagerduty:
    ports:
      - '127.0.0.1:8888:8080'

  maksatuspalvelu:
    ports:
      - '127.0.0.1:42022:22'

networks:
  default:
    name: valtionavustus_local-dev
