version: '3.3'

services:
  virkailija:
    image: va-virkailija:latest
    container_name: va-virkailija
    hostname: va-virkailija
    volumes:
      - /dev/urandom:/dev/random
    ports:
      - '8081:8081'
    depends_on:
      - hakija
      - fakesmtp
      - maksatuspalvelu
    networks:
      - subnet-private

  hakija:
    image: va-hakija:latest
    container_name: va-hakija
    hostname: va-hakija
    volumes:
      - /dev/urandom:/dev/random
    ports:
      - '8080:8080'
    depends_on:
      - db
      - fakesmtp
    networks:
      - subnet-private

  db:
    image: postgres:12.2
    volumes:
      - ./scripts/postgres-docker/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    hostname: va-postgres
    ports:
      - '5432:5432'
    networks:
      - subnet-private
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_USER: 'va'
      POSTGRES_PASSWORD: 'va'
      PGDATA: '/tmp/'

  fakesmtp:
    image: munkyboy/fakesmtp
    hostname: fakesmtp
    networks:
      - subnet-private

  maksatuspalvelu:
    image: atmoz/sftp
    hostname: maksatuspalvelu
    volumes:
      - ./maksatuspalvelu/initialize-maksatuspalvelu.sh:/etc/sftp.d/initialize-maksatuspalvelu.sh
      - ./maksatuspalvelu/identity/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
      - ./maksatuspalvelu/identity/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
    ports:
      - '42022:22'
    command: demo:pass:1001:100
    networks:
      - subnet-private

networks:
  subnet-private:
