version: '3.9'

services:
  dns:
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: ["/usr/sbin/named", "-4", "-g", "-d6"]
    hostname: dns
    ports:
      - "53:53/udp"
    volumes:
      - ./bind9/named.conf:/etc/bind/named.conf
      - ./bind9/oph.fi:/etc/bind/oph.fi
