- name: Add Jenkins build script
  template: src=jenkins-cibuild.bash.j2 dest=/usr/local/bin/jenkins-cibuild.bash owner=root group=root mode=0755

- name: Install Docker apt repo key
  apt_key: keyserver=p80.pool.sks-keyservers.net id=36A1D7869245C8950F966E92D8576A8BA88D21E9

- name: Add Docker apt repository
  apt_repository: repo='deb https://get.docker.com/ubuntu docker main' state=present

- name: Install Docker
  apt: state=installed pkg=lxc-docker force=yes

- name: Add "{{ jenkins_user }}" user to docker group
  user: name="{{ jenkins_user }}" groups=docker

- name: Install g++ for jest
  apt: state=installed pkg=g++