- name: Create www group
  group: name=www state=present

- name: Create www user
  user: name=www comment="WWW user" group=www

- name: Create www-data group
  group: name=www-data state=present

- name: Create va-deploy user
  user: name=va-deploy comment="User for application deploys" group=www-data

- name: Create application dir
  file: path={{ data_dir }}/www owner=www group=www-data state=directory mode=0775

- name: Create secret config dir
  file: path={{ data_dir }}/www/secret owner=www group=www state=directory mode=0700

- name: Create dumps dir
  file: path={{ data_dir }}/www/dumps owner=www group=www-data state=directory mode=0775

- name: Create logs dir
  file: path={{ logs_dir }}/valtionavustus owner=www group=www state=directory

- name: Add script to start and stop the application
  template: src=va_app.bash.j2 dest=/usr/local/bin/va_app.bash owner=root group=root mode=0755

- name: Allow va-deploy to start and stop the application
  lineinfile: 'dest=/etc/sudoers line="va-deploy ALL=(ALL) NOPASSWD: /usr/local/bin/va_app.bash" validate="visudo -cf %s"'

- name: Add script to run arbitrary SQL file to our db
  template: src=run_sql.bash.j2 dest=/usr/local/bin/run_sql.bash owner=postgres group=postgres mode=0700

- name: Allow va-deploy to run SQL scripts
  lineinfile: 'dest=/etc/sudoers line="va-deploy ALL=(postgres) NOPASSWD: /usr/local/bin/run_sql.bash" validate="visudo -cf %s"'

- name: Add script to dump database contents
  template: src=dump_database_to_sql.bash.j2 dest=/usr/local/bin/dump_database_to_sql.bash owner=postgres group=postgres mode=0700
