adminusers:
  pam:
    state: present
    name: Petri Ämmälä
  Silvast:
    state: present
    name: Anne-Mari Silvast
  tkareine:
    state: present
    name: Tuomas Kareinen
  wallops:
    state: present
    name: WallOps
