- name: Make SSL certificate dir for the server
  file: path=/etc/pki/domain/certs state=directory owner=root group=haproxy mode=0750

- name: Check if local certs are available
  local_action: stat path="{{certs_dir}}"
  sudo: no
  register: certs_dir_info

- name: Fail if no certs
  fail: msg='{{certs_dir}} dir not available'
  when: certs_dir_info.stat.isdir is not defined or certs_dir_info.stat.isdir == False

- name: Get cert list
  local_action: command ls -Al {{certs_dir}}
  sudo: no
  register: cert_files
  changed_when: False

- name: List certs
  debug: var=cert_files.stdout_lines

- name: Copy SSL certificates to the server
  copy: src={{certs_dir}} dest=/etc/pki/domain/certs/ owner=root group=haproxy mode=0640
