- name: Create ha proxy configuration directory for VA
  file: path=/etc/haproxy/va state=directory owner=root mode=0755

- name: Copy error pages into config
  copy: src=errors dest=/etc/haproxy/va owner=root mode=0644

- name: Haproxy need syslog UDP listening on
  lineinfile: dest=/etc/rsyslog.conf regexp="\$ModLoad imudp" line="$ModLoad imudp" backup=yes
  notify: Restart rsyslog

- name: Haproxy need syslog UDP listening on
  lineinfile: dest=/etc/rsyslog.conf regexp="\$ModLoad imudp" line="$ModLoad imudp" backup=yes
  notify: Restart rsyslog

- lineinfile: dest=/etc/rsyslog.conf regexp="\$UDPServerRun 514" line="$UDPServerRun 514" backup=yes
  notify: Restart rsyslog

- name: Config haproxy log
  template: src=haproxy_syslog.conf.j2 dest=/etc/rsyslog.d/haproxy.conf owner=root group=root mode=0644
  notify: Restart rsyslog

- name: Allow port 80 access in firewall (RedHat)
  firewalld: immediate=true port=80/tcp permanent=true state=enabled
  when: ansible_os_family == 'RedHat'

- name: Allow port 443 access in firewall (RedHat)
  firewalld: immediate=true port=443/tcp permanent=true state=enabled
  when: ansible_os_family == 'RedHat'
