- hosts: oph-va-app-test01.csc.fi
  sudo: yes
  vars:
    app_profile: va-test
    dbname: va-qa
  roles:
  - {role: ssh.init, tags: ['ssh']}
  - common
  - valtionavustus.app

- hosts: oph-va-app-prod01.csc.fi
  sudo: yes
  vars:
    app_profile: va-prod
    dbname: va-prod
  roles:
  - {role: ssh.init, tags: ['ssh']}
  - common
  - valtionavustus.app

- hosts: oph-va-lb-prod01.csc.fi
  sudo: yes
  vars_files: ['loadbalancer-prod.yml']
  roles:
  - {role: ssh.init, tags: ['ssh']}
  - {role: common}
  - {role: 3rdparty/info.haproxy, tags: ['update']}
  - {role: ssl-cert, tags: ['install', 'certs']}
  - {role: va-haproxy, tags: ['update']}

- hosts: oph-va-ci-test01.csc.fi
  sudo: yes
  roles:
  - {role: ssh.init, tags: ['ssh']}
  - node
  - common
  - buildmachine
  - valtionavustus.build
  - 3rdparty/Stouts.jenkins
  - valtionavustus.deploy
