- hosts: va-dev
  user: cloud-user
  sudo: yes
  vars:
    app_profile: va-dev
    dbname: va-dev
  roles:
  - valtionavustus.app.logical.volumes
  - valtionavustus.app

- hosts: oph-va-app-test01.csc.fi
  sudo: yes
  vars:
    app_profile: va-test
    dbname: va-qa
  roles:
  - ssh.init
  - common
  - valtionavustus.app

- hosts: oph-va-app-prod01.csc.fi
  sudo: yes
  vars:
    app_profile: va-prod
    dbname: va-prod
  roles:
  - ssh.init
  - common
  - valtionavustus.app

- hosts: va-loadbalancer-dev
  user: cloud-user
  sudo: yes
  vars_files: ['loadbalancer-dev.yml']
  roles:
  - {role: ssh.init}
  - {role: common}
  - {role: 3rdparty/info.haproxy, tags: ['update']}
  - {role: ssl-cert, tags: ['install', 'certs']}
  - {role: va-haproxy, tags: ['update']}

- hosts: oph-va-lb-prod01.csc.fi
  sudo: yes
  vars_files: ['loadbalancer-prod.yml']
  roles:
  - {role: ssh.init}
  - {role: common}
  - {role: 3rdparty/info.haproxy, tags: ['update']}
  - {role: ssl-cert, tags: ['install', 'certs']}
  - {role: va-haproxy, tags: ['update']}

- hosts: oph-va-ci-test01.csc.fi
  sudo: yes
  roles:
  - ssh.init
  - common
  - buildmachine
  - valtionavustus.build
  - 3rdparty/Stouts.jenkins
  - valtionavustus.deploy

- hosts: va-build
  user: cloud-user
  sudo: yes
  vars:
     database_dumps_dir: /mnt/db-dumps
  roles:
  - buildmachine.logical.volumes
  - buildmachine
  - valtionavustus.build
  - 3rdparty/Stouts.jenkins
  - valtionavustus.deploy
