- hosts: va-dev
  user: cloud-user
  sudo: yes
  vars:
    app_profile: va-dev
    dbname: va-dev
  roles:
  - valtionavustus.vmware.app

- hosts: va-test
  user: cloud-user
  sudo: yes
  vars:
    app_profile: test
    dbname: va-qa
  roles:
  - valtionavustus.app

- hosts: oph-va-app-test01.csc.fi
  sudo: yes
  vars:
    security_sudoers_passwordless: "{{ sudoers }}"
    security_autoupdate_enabled: false
    app_profile: va-test
    dbname: va-qa
  roles:
  - valtionavustus.vmware.app
  - geerlingguy.security

- hosts: va-prod
  user: cloud-user
  sudo: yes
  vars:
    app_profile: prod
    dbname: va-prod
  roles:
  - valtionavustus.app

- hosts: oph-va-app-prod01.csc.fi
  sudo: yes
  vars:
    security_sudoers_passwordless: "{{ sudoers }}"
    security_autoupdate_enabled: false
    app_profile: va-prod
    dbname: va-prod
  roles:
  - valtionavustus.vmware.app
  - geerlingguy.security

- hosts: va-loadbalancer-dev
  user: cloud-user
  sudo: yes
  vars_files: ['loadbalancer-dev.yml']
  roles:
  - {role: ssh.init}
  - {role: common}
  - {role: 3rdparty/info.haproxy, tags: ['update']}
  - {role: ssl-cert, tags: ['install', 'certs']}
  - {role: va-haproxy, tags: ['update']}

- hosts: oph-va-lb-prod01.csc.fi
  sudo: yes
  vars:
    security_sudoers_passwordless: "{{ sudoers }}"
    security_autoupdate_enabled: false
  vars_files: ['loadbalancer-prod.yml']
  roles:
  - {role: ssh.init}
  - {role: common}
  - {role: 3rdparty/info.haproxy, tags: ['update']}
  - {role: ssl-cert, tags: ['install', 'certs']}
  - {role: va-haproxy, tags: ['update']}
  - {role: geerlingguy.security}

- hosts: va-build
  user: cloud-user
  sudo: yes
  roles:
  - buildmachine
  - valtionavustus.build
  - 3rdparty/Stouts.jenkins
  - valtionavustus.deploy
  - 3rdparty/debops.pki
  - 3rdparty/debops.nginx
  - 3rdparty/nodesource.node
