- hosts: va_app va_loadbalancer va_build
  sudo: yes
  roles:
  - {role: ssh.init, tags: ['ssh']}

- hosts: va_app
  sudo: yes
  roles:
  - {role: common, tags: ['common']}
  - {role: valtionavustus.app, tags: ['app']}

- hosts: va_loadbalancer
  sudo: yes
  roles:
  - {role: common}
  - {role: 3rdparty/info.haproxy, tags: ['update']}
  - {role: ssl-cert, tags: ['install', 'certs']}
  - {role: va-haproxy, tags: ['update']}

- hosts: va_build
  sudo: yes
  roles:
  - {role: node, tags: ['nodejs']}
  - {role: common, tags: ['common']}
  - {role: buildmachine, tags: ['buildmachine']}
  - {role: valtionavustus.build, tags: ['build']}
  - {role: 3rdparty/Stouts.jenkins, tags: ['jenkins']}
  - {role: valtionavustus.deploy, tags: ['deploy']}
