- hosts: va_app
  sudo: yes
  roles:
  - {role: ssh.init, tags: ['ssh']}
  - common
  - valtionavustus.app

- hosts: va_loadbalancer
  sudo: yes
  roles:
  - {role: ssh.init, tags: ['ssh']}
  - {role: common}
  - {role: 3rdparty/info.haproxy, tags: ['update']}
  - {role: ssl-cert, tags: ['install', 'certs']}
  - {role: va-haproxy, tags: ['update']}

- hosts: va_build
  sudo: yes
  roles:
  - {role: ssh.init, tags: ['ssh']}
  - {role: node, tags: ['nodejs']}
  - common
  - buildmachine
  - valtionavustus.build
  - 3rdparty/Stouts.jenkins
  - valtionavustus.deploy
