---

- name: jenkins-install | Add apt key
  apt_key: url={{ jenkins_apt_key }} id={{jenkins_apt_key_id}}
  become: yes

- name: jenkins-install | Add apt repo
  apt_repository: repo="{{ jenkins_apt_repository }}" update_cache=yes
  become: yes

- name: jenkins-install | Install jenkins
  apt:
    pkg: [curl, jenkins]
  become: yes

- name: jenkins-install | Install additional deb packages
  apt:
    pkg: "{{ jenkins_apt_packages }}"
  become: yes

- name: jenkins-install | Setup passlib
  apt: pkg=python-passlib
  become: yes
  when: jenkins_proxy_auth

# vim:sw=2
