---

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == 'RedHat'

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}-{{ ansible_lsb.codename }}.yml"
  when: ansible_os_family == 'Debian'
  
- include: jenkins.yml
  when: jenkins_enabled
  tags: [jenkins]

- include: checkjobs.yml
  when: jenkins_check_jobs | length > 0
  tags: [jenkins]
  
- name: Copy Dockerfile
  template: src=Dockerfile.j2 dest={{ docker_files_generated_directory }}/Dockerfile mode=0777
  when: docker_files_enable
  
- name: Copy build.sh
  template: src=build.sh.j2 dest={{ docker_files_generated_directory }}/build.sh mode=0777
  when: docker_files_enable

- name: upload buildstatus
  include: buildstatus.yml

- name: Cronjob to clean yum cache to prevent /var partition from running out of space
  cron:
    name: Clean yum cache periodically
    minute: "0"
    hour: "8"
    user: root
    job: "/usr/bin/yum clean all"
