- name: Autoaccept license for Java
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install Java
  action: apt pkg=oracle-java8-installer state=latest install_recommends=yes

- name: Set Java Env
  action: apt pkg=oracle-java8-set-default state=latest install_recommends=yes