- name: Restart systemd journald
  service: name=systemd-journald state=restarted

- name: Reload iptables
  command: /etc/rc.d/rc.firewall

- name: Init alias db
  command: newaliases

- name: Reload systemd
  systemd:
    daemon_reload: yes
