version: '3.9'

services:
  tunnel:
    build:
      context: ./
      dockerfile: ./Dockerfile.psql-tunnel
    ports:
      - "127.0.0.1:40077:5432/tcp"
    healthcheck:
      test: [ "CMD", "nc", "-z", "-v", "localhost", "5432" ]
      interval: 5s
      timeout: 2s
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
      - $HOME/.aws/config:/root/.aws/config:ro
    environment:
      - AWS_PROFILE
