# nginx configs:
nginx_jenkins_http_auth_basic_filename: /etc/nginx/private/va-jenkins-nginx-passwd

nginx_root_dir: /srv/www/sites/va-build/public

nginx_vhosts:
  - server_name: "{{ ansible_nodename }}"
    root: "{{ nginx_root_dir }}"
    listen: "80 default_server"
    extra_parameters: |
      location '/' {
        proxy_pass "{{ jenkins_url }}";
        proxy_read_timeout 90;
        auth_basic "va-dev";
        auth_basic_user_file "{{ nginx_jenkins_http_auth_basic_filename }}";
      }

# Jenkins configs:
jenkins_home: /data/jenkins

#latest
#jenkins_apt_key: "http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key"
#jenkins_apt_repository: "deb http://pkg.jenkins-ci.org/debian binary/"
#latest stable
jenkins_apt_key: http://pkg.jenkins-ci.org/debian-stable/jenkins-ci.org.key
jenkins_apt_key_id: D50582E6
jenkins_apt_repository: deb http://pkg.jenkins-ci.org/debian-stable binary/

jenkins_apt_packages: []

jenkins_proxy: true
jenkins_proxy_ssl: true
jenkins_proxy_hostname: "dev.valtionavustukset.oph.fi"
jenkins_proxy_port: 443
jenkins_http_host: "{{ ansible_nodename }}"
jenkins_http_port: 8000

jenkins_plugins:
  - ansicolor
  - github
  - git
  - greenballs
  - email-ext
  - junit
  - slack

# System config
# =============
jenkins_system_config:
  admin_email: "{{ alert_mail_recipient }}"
