- name: Wait until Jenkins web API is available
  shell: curl --head --silent http://{{ jenkins_http_host }}:{{ jenkins_http_port }}{{ jenkins_prefix }}/cli/
  delay: 10
  retries: 12
  until: result.stdout.find("200 OK") != -1
  register: result
  check_mode: no

- name: Kludge to force the Jenkins job installation. For some reason it does not get triggered properly.
  command: "{{jenkins_home}}/jobs/job.sh {{item.name}}"
  with_items: "{{ jenkins_jobs }}"

- name: Make sure Jenkins user .ssh exists
  sudo_user: "{{ jenkins_user }}"
  file: path=~{{ jenkins_user }}/.ssh state=directory mode=0700

- name: Make sure Jenkins user .ssh/known_hosts exists
  sudo_user: "{{ jenkins_user }}"
  file: "path=~{{ jenkins_user }}/.ssh/known_hosts state=touch mode=0600"

- name: Remove the old SSH host key of application servers from to ~{{ jenkins_user }}/.ssh/known_hosts
  sudo_user: "{{ jenkins_user }}"
  shell: "ssh-keygen -R {{ item }}"
  with_items: groups['va_app']

- name: Add the new SSH host key of application servers to ~{{ jenkins_user }}/.ssh/known_hosts for deploys
  sudo_user: "{{ jenkins_user }}"
  shell: "ssh-keyscan -H {{ item }} >> ~{{ jenkins_user }}/.ssh/known_hosts"
  with_items: groups['va_app']

- name: Generate new SSH key for "{{ jenkins_user }}" user for application deploys
  user: name="{{ jenkins_user }}" generate_ssh_key=yes ssh_key_file=.ssh/id_deploy

- name: Fetch ~"{{ jenkins_user }}".ssh/id_deploy.pub for adding it to app server machine
  fetch: src=~{{ jenkins_user }}/.ssh/id_deploy.pub dest=/tmp/{{ ansible_hostname }}-{{ jenkins_user }}.pub flat=yes fail_on_missing=yes

- name: Add deploy private key for github.com to ssh config
  ssh_config: user={{ jenkins_user}} remote_user=git host=github.com hostname=github.com
              identity_file=~{{ jenkins_user }}/.ssh/id_deploy port=22 state=present

- name: Add new jenkins public SSH key to deployer account on app server machines
  authorized_key: user="va-deploy"
                  key='{{ lookup("file", "/tmp/" + ansible_hostname + "-" + jenkins_user + ".pub") }}'
  delegate_to: "{{ item }}"
  with_items: groups['va_app']
  remote_user: "{{ lookup('env','USER') }}"
  when: not ansible_check_mode

- name: Add new jenkins public SSH key to Postgresql account on app server machines for backups
  authorized_key: user="postgres"
                  key='{{ lookup("file", "/tmp/" + ansible_hostname + "-" + jenkins_user + ".pub") }}'
  delegate_to: "{{ item }}"
  with_items: groups['va_app']
  remote_user: "{{ lookup('env','USER') }}"
  when: not ansible_check_mode
