app_secrets_vault_file: "{{ playbook_dir }}/config/secret-{{ app_profile }}-vault.edn"
logs_dir: /logs
data_dir: /data
postgresql_version: 9.4
postgresql_backup_dir: /postgresql-backups
postgresql_backup_hour: 01
postgresql_backup_minute: 00
postgresql_backup_mail_recipient: "{{ alert_mail_recipient }}"
postgresql_backup_remote_rsync_path: None
postgresql_pg_hba_local_ipv4: false
postgresql_pg_hba_conf:
      - host all all 127.0.0.1/32 md5
