version: 0.0
os: linux
files:
  - source: va-hakija/target/uberjar/hakija-0.1.0-SNAPSHOT-standalone.jar
    destination: /home/ec2-user/va-hakija/
hooks:
  ApplicationStart:
    - location: ci/dev_start_hakija.sh
      timeout: 10
      runas: ec2-user
