- name: Debug hostvars
  debug: var=hostvars

- name: Add Java repository to sources
  action: apt_repository repo='ppa:webupd8team/java'

- name: Update APT package cache
  apt: update_cache=yes cache_valid_time=3600

- name: Upgrade packages
  apt: upgrade=safe

- name: Install required packages
  apt: state=installed pkg={{ item }}
  with_items: ubuntu_common_required_packages

- name: Disable RepeatedMsgReduction of rsyslogd because it is buggy
  lineinfile: dest=/etc/rsyslog.conf regexp="^\$RepeatedMsgReduction" line="$RepeatedMsgReduction off" backup=yes
  register: rsyslog_config

- name: Restart rsyslog if config was changed
  service: name=rsyslog state=restarted
  when: rsyslog_config.changed

- name: Install rng-tools to avoid /dev/random exhaust
  apt: name=rng-tools
  notify: Restart RNG

- lineinfile: dest=/etc/default/rng-tools line="HRNGDEVICE=/dev/urandom"
  notify: Restart RNG

- name: Force rng-tools restart
  service: name=rng-tools state=restarted enabled=yes

- name: Gather test application server names to list
  debug:
    msg: |
          {% set comma = joiner(",") %}
          {% for server in groups['va_backend'] -%}
              {{ comma() }}{{ server }}
          {%- endfor %}
  register: test_application_server_names


- name: Gather production application server names to list
  debug:
    msg: |
          {% set comma = joiner(",") %}
          {% for server in groups['prod-va_backend'] -%}
              {{ comma() }}{{ server }}
          {%- endfor %}
  register: production_application_server_names
