- name: Restart ssh
  debug: msg="Triggering OS specific ssh service restart"
  notify:
    - Restart ssh (Debian)
    - Restart ssh (RedHat)
  changed_when: true

- name: Restart ssh (Debian)
  service: name=ssh state=restarted
  when: ansible_os_family == 'Debian'

- name: Restart ssh (RedHat)
  service: name=sshd state=restarted
  when: ansible_os_family == 'RedHat'
