version: '3.3'

services:
  server-dev:
    image: postgres:12.2
    container_name: va-postgres
    profiles:
      - dev
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '42042:5432'
    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: va
      POSTGRES_PASSWORD: va
      PGDATA: '/tmp/'
  server-restore-backup:
    image: postgres:12.2
    container_name: va-postgres
    profiles:
      - restore-backup
    volumes:
      - ./init-db-restore.sql:/docker-entrypoint-initdb.d/init.sql
      - va-postgres-pgdata:/var/lib/postgresql/data
    ports:
      - '42042:5432'
    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: va
      POSTGRES_PASSWORD: va

volumes:
  va-postgres-pgdata:
