---
apache_server_root: /etc/httpd
apache_listen_port: "{{ jenkins_proxy_port }}"
jenkins_configuration: /etc/sysconfig/jenkins
jenkins_root: /usr/lib/jenkins

apache_ports_configuration_items:
  - {
    regexp: "^Listen ",
    line: "Listen {{ apache_listen_port }}"
  }
  - {
    regexp: "^NameVirtualHost ",
    line: "NameVirtualHost *:{{ apache_listen_port }}"
  }
