- name: Install psycopg2
  apt: name=python-psycopg2

- name: Ensure database is created
  sudo: yes
  sudo_user: postgres
  postgresql_db: name={{dbname}}
                 encoding='UTF-8'

- name: Ensure user has access to database
  sudo: yes
  sudo_user: postgres
  postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL

- name: Ensure user does not have unnecessary privilege
  sudo: yes
  sudo_user: postgres
  postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB