- name: Install psycopg2
  apt: name=python-psycopg2

- name: Create Postgresql backup directory
  file: path={{ postgresql_backup_dir }} owner=postgres group=postgres state=directory

- name: Restart PostgreSQL to get backup settings in effect
  service: name=postgresql state=restarted

- name: Ensure database is created
  sudo: yes
  sudo_user: postgres
  postgresql_db: name={{dbname}}
                 encoding='UTF-8'

- name: Ensure users have access to database
  sudo: yes
  sudo_user: postgres
  postgresql_user: db={{item.dbname}} name={{item.dbuser}} password={{item.dbpassword}} priv=ALL
  with_items: db_accounts

- name: Ensure users do not have unnecessary privileges
  sudo: yes
  sudo_user: postgres
  postgresql_user: name={{item.dbuser}} role_attr_flags=SUPERUSER,NOCREATEDB  # Note: we might want to have NOSUPERUSER
  with_items: db_accounts
