---
# Create our virtual machines on Pouta.csc.fi
#
# You'll need to download and source your credentials before this will work:
#  https://research.csc.fi/pouta-credentials
#
- name: Set up servers to Pouta with ansible
  # The OpenStack modules only work with your local machine.
  hosts: localhost
  # And it doesn't use local facts
  gather_facts: false

  vars:
    pouta_username: "{{ lookup('env','OS_USERNAME') }}"
    pouta_password: "{{ lookup('env','OS_PASSWORD') }}"
    tenant_name: "{{ lookup('env','OS_TENANT_NAME') }}"
    auth_url: "{{ lookup('env','OS_AUTH_URL') }}"

    # You can see the available flavors and images with pouta-venv/bin/nova flavor-list && pouta-venv/bin/nova image-list
    pouta_tiny: 1a0f1143-47b5-4e8a-abda-eba52ae3c5b9
    pouta_mini: 417fcb76-884b-405f-a4f4-8bce27058e4a
    pouta_small: 9e2c9a54-af51-40be-a9d9-977d6b6d8958
    pouta_ubuntu_14_04: Ubuntu-14.04
    pouta_centos_7_0: CentOS-7.0

    pouta_key: "{{ lookup('env', 'USER') }}"
    va_network: e15cfa1c-a214-415a-8909-e270b3ec344b

  tasks:
    - { include: tasks/create_machine.yml,
        machine_name: va-build,
        pouta_flavor_id: "{{ pouta_small }}",
        pouta_image_name: "{{ pouta_ubuntu_14_04 }}",
        va_ansible_host_groups: 'va_build',
        va_security_groups: 'qa-common,va-build'
      }
    - { include: tasks/create_machine.yml,
        machine_name: va-test,
        pouta_flavor_id: "{{ pouta_mini }}",
        va_ansible_host_groups: 'va_backend',
        pouta_image_name: "{{ pouta_ubuntu_14_04 }}",
        va_security_groups: 'qa-common,qa-va-app'
      }
    - { include: tasks/create_machine.yml,
        machine_name: va-loadbalancer-dev,
        pouta_flavor_id: "{{ pouta_tiny }}",
        pouta_image_name: "{{ pouta_centos_7_0 }}",
        floating_ip: 86.50.170.86,
        va_ansible_host_groups: 'gateways',
        va_security_groups: 'qa-loadbalancer-secgroup'
      }
    - { include: tasks/create_machine.yml,
        machine_name: va-dev,
        pouta_flavor_id: "{{ pouta_mini }}",
        pouta_image_name: "{{ pouta_centos_7_0 }}",
        va_ansible_host_groups: "va_app,va_app_dev",
        va_security_groups: 'qa-common,qa-va-app'
      }
    - { include: tasks/create_machine.yml,
        machine_name: va-prod,
        pouta_flavor_id: "{{ pouta_mini }}",
        pouta_image_name: "{{ pouta_ubuntu_14_04 }}",
        va_ansible_host_groups: 'prod-va_backend',
        va_security_groups: 'prod-common,prod-va-app'
      }
    - { include: tasks/attach_persistent_volumes_if_needed.yml,
        machine_name: va-test,
        volume_ids: [9410dc1b-201a-4126-b11f-a2450e6f8396]
      }
    - { include: tasks/attach_persistent_volumes_if_needed.yml,
        machine_name: va-prod,
        volume_ids: [f10a7b7d-8d24-44af-ad80-4d97b09b3e9c]
      }
    - { include: tasks/attach_persistent_volumes_if_needed.yml,
        machine_name: va-build,
        volume_ids: [6395f20b-509a-4336-8c41-189c7d4e6fb2]
      }
