---
# Create our virtual machines on Pouta.csc.fi
#
# You'll need to download and source your credentials before this will work:
#  https://research.csc.fi/pouta-credentials
#
- name: Set up servers to Pouta with ansible
  # The OpenStack modules only work with your local machine.
  hosts: localhost
  # And it doesn't use local facts
  gather_facts: false

  vars:
    pouta_username: "{{ lookup('env','OS_USERNAME') }}"
    pouta_password: "{{ lookup('env','OS_PASSWORD') }}"
    tenant_name: "{{ lookup('env','OS_TENANT_NAME') }}"
    auth_url: "{{ lookup('env','OS_AUTH_URL') }}"

    # You can see the available flavors and images with pouta-venv/bin/nova flavor-list && pouta-venv/bin/nova image-list
    pouta_tiny: 1a0f1143-47b5-4e8a-abda-eba52ae3c5b9
    #pouta_centos65: cc001620e8b5ac640fed8f737eaaeefc78a6dd89
    pouta_ubuntu_14_04: 77cdde39-9b75-4a77-9ec4-77ea39d22c23

    pouta_key: "{{ lookup('env', 'USER') }}"
    va_security_groups: va-initial-secgroup
    va_network: e15cfa1c-a214-415a-8909-e270b3ec344b

  tasks:
    - { include: tasks/create_machine_if_needed.yml,
        machine_name: va-build,
        va_floating_ip: 86.50.169.218
      }
    - { include: tasks/create_machine_if_needed.yml,
        machine_name: va-test,
        va_floating_ip: 86.50.168.174
      }
    - { include: tasks/attach_persistent_volumes_if_needed.yml,
        machine_name: va-test,
        volume_ids: [9410dc1b-201a-4126-b11f-a2450e6f8396]
      }
