- hosts: va-test
  user: cloud-user
  sudo: yes
  vars:
    app_profile: test
    persistent_volume_devices: /dev/vdc
    logical_volumes:
      logs:
        filesystem: xfs
        size: 100g
        mount_point: /logs
      postgresql_data:
        filesystem: xfs
        size: 100g
        mount_point: /var/lib/postgresql
      postgresql_config:
        filesystem: xfs
        size: 10g
        mount_point: /etc/postgresql
      data:
        filesystem: xfs
        size: 100g
        mount_point: /data
      home2:
        filesystem: xfs
        size: 100g
        mount_point: /home2
    postgresql_version: 9.4
    postgresql_flavor: pgdg
  roles:
  - ssh.init
  - common
  - logical.volumes
  - 3rdparty/postgresql
  - postgresql.db
  - java8
  - valtionavustus.app

- hosts: va-build
  user: cloud-user
  sudo: yes
  roles:
  - ssh.init
  - common
  - buildmachine
  - valtionavustus.build
  - java8
  - 3rdparty/Stouts.jenkins
  - valtionavustus.deploy
  - 3rdparty/debops.pki
  - 3rdparty/debops.nginx
  - 3rdparty/nodesource.node