
- hosts: all
  user: cloud-user
  sudo: yes
  roles:
  - common

- hosts: va-build
  user: cloud-user
  sudo: yes
  roles:
  - buildmachine
  - Stouts.jenkins
  - debops.nginx

- hosts: va-test
  user: cloud-user
  sudo: yes
  vars:
    app_profile: test
    mountdisks:
      logs:
        mount_point: /logs
        disk_label: va-test-logs
        filesystem: xfs
      data:
        mount_point: /data
        disk_label: va-test-data
        filesystem: xfs
  roles:
  - mountdisks
  - java8
  - postgres
  - nodesource.node
  - testmachine
