- hosts: va-test
  user: cloud-user
  sudo: yes
  vars:
    app_profile: test
    dbname: va-qa
  roles:
  - valtionavustus.app

- hosts: va-prod
  user: cloud-user
  sudo: yes
  vars:
    app_profile: prod
    dbname: va-prod
  roles:
  - valtionavustus.app

- hosts: va-build
  user: cloud-user
  sudo: yes
  roles:
  - buildmachine
  - valtionavustus.build
  - 3rdparty/Stouts.jenkins
  - valtionavustus.deploy
  - 3rdparty/debops.pki
  - 3rdparty/debops.nginx
  - 3rdparty/nodesource.node