- hosts: va-test
  user: cloud-user
  sudo: yes
  vars:
    app_profile: test
    dbname: va-qa
  roles:
  - valtionavustus.app

- hosts: va-test-centos
  user: cloud-user
  sudo: yes
  vars:
    app_profile: va-test-centos
    dbname: va-qa
  roles:
  - valtionavustus.vmware.app

- hosts: va-prod
  user: cloud-user
  sudo: yes
  vars:
    app_profile: prod
    dbname: va-prod
  roles:
  - valtionavustus.app

- hosts: loadbalancer-test-centos
  user: cloud-user
  sudo: yes
  vars_files: ['loadbalancer-prod.yml']
  roles:
  - {role: ssh.init}
  - {role: common}
  - {role: 3rdparty/info.haproxy, tags: ['update']}
  - {role: ssl-cert, tags: ['install', 'certs']}
  - {role: va-haproxy, tags: ['update']}

- hosts: va-build
  user: cloud-user
  sudo: yes
  roles:
  - buildmachine
  - valtionavustus.build
  - 3rdparty/Stouts.jenkins
  - valtionavustus.deploy
  - 3rdparty/debops.pki
  - 3rdparty/debops.nginx
  - 3rdparty/nodesource.node