- hosts: va-test
  user: cloud-user
  sudo: yes
  vars:
    app_profile: test
  roles:
  - valtionavustus.app

- hosts: va-build
  user: cloud-user
  sudo: yes
  roles:
  - ssh.init
  - common
  - buildmachine
  - valtionavustus.build
  - java8
  - 3rdparty/Stouts.jenkins
  - valtionavustus.deploy
  - 3rdparty/debops.pki
  - 3rdparty/debops.nginx
  - 3rdparty/nodesource.node