
- hosts: all
  user: cloud-user
  sudo: yes
  roles:
  - common

- hosts: va-build
  user: cloud-user
  sudo: yes
  roles:
  - buildmachine
  - Stouts.jenkins
  - debops.pki
  - debops.nginx

- hosts: va-test
  user: cloud-user
  sudo: yes
  vars:
    app_profile: test
    postgresql_version: 9.4
    postgresql_flavor: pgdg
    persistent_volume_devices: /dev/vdc
    logical_volumes:
      logs:
        filesystem: xfs
        size: 100g
        mount_point: /logs
      data:
        filesystem: xfs
        size: 100g
        mount_point: /data
  roles:
  - logical.volumes
  - java8
  - postgresql
  - postgresql.db
  - nodesource.node
  - valtionavustus.app
