
- hosts: all
  user: cloud-user
  sudo: yes
  roles:
  - common

- hosts: va-build
  user: cloud-user
  sudo: yes
  roles:
  - buildmachine
  - Stouts.jenkins
  - debops.nginx

- hosts: va-test
  user: cloud-user
  sudo: yes
  vars:
    app_profile: test
  roles:
  - java8
  - postgres
  - testmachine
