
- hosts: all
  user: cloud-user
  sudo: yes
  roles:
  - common

- hosts: va-build
  user: cloud-user
  sudo: yes
  roles:
  - buildmachine
  - Stouts.jenkins
  - debops.pki
  - debops.nginx

- hosts: va-test
  user: cloud-user
  sudo: yes
  vars:
    app_profile: test
    persistent_volume_devices: /dev/vdc
    logical_volumes:
      logs:
        filesystem: xfs
        size: 100g
        mount_point: /logs
      postgresql_data:
        filesystem: xfs
        size: 100g
        mount_point: /var/lib/postgresql
      postgresql_config:
        filesystem: xfs
        size: 10g
        mount_point: /etc/postgresql
      home2:
        filesystem: xfs
        size: 100g
        mount_point: /home2
    postgresql_version: 9.4
    postgresql_flavor: pgdg
  roles:
  - logical.volumes
  - postgresql
  - postgresql.db
  - java8
  - nodesource.node
  - valtionavustus.app
