- name: Install apache2-utils to get httpaswd (Debian)
  apt:  pkg=apache2-utils state=installed
  when: ansible_os_family == 'Debian'

- name: Install httpd-tools to get httpaswd (RedHat)
  yum:  pkg=httpd-tools state=installed
  when: ansible_os_family == 'RedHat'

- name: Install git (Debian)
  apt:  pkg=git state=latest install_recommends=yes
  when: ansible_os_family == 'Debian'

- name: Install git (RedHat)
  yum:  pkg=git state=latest
  when: ansible_os_family == 'RedHat'

- name: Allow port 8000 access in firewall (RedHat)
  firewalld: immediate=true port=8000/tcp permanent=true state=enabled
  when: ansible_os_family == 'RedHat'

- name: Add script to add users manually
  template: src=add_va_jenkins_user.bash.j2 dest=/usr/local/bin/add_va_jenkins_user.bash owner=root group=root mode=0755

- name: Remove previous OPH artifactory IP mapping from /etc/hosts
  lineinfile: dest=/etc/hosts regexp='^[0-9\.]* artifactory.oph.ware.fi$' state=absent owner=root group=root mode=0644

- name: Add OPH artifactory IP mapping to /etc/hosts
  lineinfile: dest=/etc/hosts line='178.217.133.55 artifactory.oph.ware.fi' owner=root group=root mode=0644
