letsencrypt_certbot_user: certbot
letsencrypt_certbot_group: certbot
letsencrypt_certbot_root_dir: /opt/certbot
letsencrypt_certbot_logs_dir: "{{ letsencrypt_certbot_root_dir }}/logs"
letsencrypt_certbot_config_dir: "{{ letsencrypt_certbot_root_dir }}/config"
letsencrypt_certbot_renew_script: "{{ letsencrypt_certbot_root_dir }}/renew-certificate"
letsencrypt_certbot_port: 54321
letsencrypt_domains:
  - "valtionavustukset.oph.fi"
  - "statsunderstod.oph.fi"
  - "virkailija.valtionavustukset.oph.fi"
  - "testi.valtionavustukset.oph.fi"
  - "testi.virkailija.valtionavustukset.oph.fi"
  - "dev.valtionavustukset.oph.fi"
letsencrypt_primary_domain: "{{ letsencrypt_domains | first }}"
letsencrypt_combined_cert_dir: "/etc/pki/domain/certs"
letsencrypt_combined_cert: "{{ letsencrypt_combined_cert_dir }}/{{ letsencrypt_primary_domain }}.pem"

certs_dir: '../../valtionavustus-secret/certs/lb'

# ACL:s for different endpoints

loadbalancer_acl:
  - name: va_backend_qa
    condition: hdr(host) -i testi.valtionavustukset.oph.fi
  - name: va_virkailija_backend_qa
    condition: hdr(host) -i testi.virkailija.valtionavustukset.oph.fi
  - name: va_backend_prod_fi
    condition: hdr(host) -i valtionavustukset.oph.fi
  - name: va_backend_prod_sv
    condition: hdr(host) -i statsunderstod.oph.fi
  - name: va_virkailija_backend_prod
    condition: hdr(host) -i virkailija.valtionavustukset.oph.fi
  - name: va_build
    condition: hdr(host) -i dev.valtionavustukset.oph.fi
  - name: va_ip_test
    condition: hdr(host) -i 86.50.28.144
  - name: source_ip_is_reaktor
    condition: src 62.165.154.10/32
  - name: letsencrypt_acl
    condition: path_beg /.well-known/acme-challenge/

loadbalancer_response:
  - action: set-header
    param: X-Robots-Tag noindex

# Map from acl declaration to backend

loadbalancer_acl_mapping:
  - name: letsencrypt_backend
    condition: if letsencrypt_acl
  - name: va_backend_qa
    condition: if va_backend_qa
  - name: va_virkailija_backend_qa
    condition: if va_virkailija_backend_qa
  - name: va_backend_prod
    condition: if va_backend_prod_fi
  - name: va_backend_prod
    condition: if va_backend_prod_sv
  - name: va_virkailija_backend_prod
    condition: if va_virkailija_backend_prod
  - name: va_build
    condition: if va_build source_ip_is_reaktor
  - name: va_ip_test
    condition: if va_ip_test source_ip_is_reaktor

# Define backends

haproxy_backends:
- name: 'va_backend_qa'
  balance: 'source'
  server_group:
    - name: "va_app_qa"
      port: 8081
      params: ['check']
  errorfile:
    - code: 503
      file: /etc/haproxy/va/errors/503.http
  options:
    - httpchk GET /api/healthcheck HTTP/1.1\r\nHost:\ testi.valtionavustukset.oph.fi

- name: 'va_virkailija_backend_qa'
  balance: 'source'
  server_group:
    - name: "va_app_qa"
      port: 6071
      params: ['check']
  errorfile:
    - code: 503
      file: /etc/haproxy/va/errors/503.http
  options:
    - httpchk GET /api/healthcheck HTTP/1.1\r\nHost:\ testi.virkailija.valtionavustukset.oph.fi

- name: 'va_backend_prod'
  balance: 'source'
  server_group:
    - name: "va_app_prod"
      port: 8081
      params: ['check']
  errorfile:
    - code: 503
      file: /etc/haproxy/va/errors/503.http
  options:
    - httpchk GET /api/healthcheck HTTP/1.1\r\nHost:\ valtionavustukset.oph.fi

- name: 'va_virkailija_backend_prod'
  balance: 'source'
  server_group:
    - name: "va_app_prod"
      port: 6071
      params: ['check']
  errorfile:
    - code: 503
      file: /etc/haproxy/va/errors/503.http
  options:
    - httpchk GET /api/healthcheck HTTP/1.1\r\nHost:\ virkailija.valtionavustukset.oph.fi

- name: 'va_build'
  balance: 'source'
  server_group:
    - name: "va_build"
      port: 80

- name: 'va_ip_test'
  balance: 'source'
  server_group:
    - name: "va_build"
      port: 80

- name: 'letsencrypt_backend'
  balance: 'source'
  servers:
    - name: 'letsencrypt'
      ip: 127.0.0.1
      port: '{{ letsencrypt_certbot_port }}'

# Global configuration - no need to change

haproxy_frontends:
  - name: 'loadbalancer'
    maxconn: '1000'
    bind: ["{{ ansible_default_ipv4.address }}:80"]
    redirects:
      - scheme https code 301
  - name: 'loadbalancer-https'
    maxconn: '1000'
    bind: ["{{ ansible_default_ipv4.address }}:443"]
    ssl:
      cert: '/etc/pki/domain/certs/'
      ciphers: 'ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DS no-sslv3'
    acl: "{{ loadbalancer_acl }}"
    http_response: "{{ loadbalancer_response }}"

    use_backend: "{{ loadbalancer_acl_mapping }}"

haproxy_defaults:
  mode: http
  log:
    - address: 127.0.0.1
      facility: local2
      level: notice
  timeout:
      - param: 'connect'
        value: '5000ms'
      - param: 'http-request'
        value: '5000ms'
      - param: 'client'
        value: '50000ms'
      - param: 'server'
        value: '300000ms'
  options:
    - httpclose
    - forwardfor except 127.0.0.0/8
    - redispatch
    - abortonclose
    - httplog
    - dontlognull
  compression:
    algo: gzip
    type: text/html text/html;charset=utf-8 text/plain text/css text/javascript application/json application/json;charset=utf-8 application/javascript application/rtf application/pdf application/vnd.oasis.opendocument.text application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document application/vnd.oasis.opendocument.spreadsheet application/vnd.ms-excel application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
  errorfile:
      - code: 400
        file: /etc/haproxy/errors/400.http
      - code: 403
        file: /etc/haproxy/errors/403.http
      - code: 408
        file: /etc/haproxy/errors/408.http
      - code: 500
        file: /etc/haproxy/errors/500.http
      - code: 502
        file: /etc/haproxy/errors/502.http
      - code: 504
        file: /etc/haproxy/errors/504.http
