---
##
# Apache2 setup.
#

- name: Apache | Enable required Apache modules
  apache2_module: state=present name={{ item }}
  with_items:
    - proxy
    - proxy_http
    - rewrite
    - ssl
  sudo: yes


- name: Apache | Disable the default site
  action: command a2dissite 000-default
  ignore_errors: yes  
  tags: apache
      
- name: Apache | Configure Apache
  lineinfile:
    dest: "{{ apache_server_root }}/ports.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
#    validate: '/usr/sbin/apache2ctl -f %s -t'
  with_items: apache_ports_configuration_items
  sudo: yes
  tags: apache
  notify:
    - apache restart      
      
- name: Apache | Compile Apache Jenkins configuration
  template: src=apache.conf.j2 dest=/etc/apache2/sites-available/jenkins.conf
  sudo: yes  
  tags: apache

- name: Apache | Enable our Jenkins site
  action: command a2ensite jenkins
  sudo: yes  
  tags: apache
  notify:
    - apache restart
