- name: Set ssh MaxStartUps
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^MaxStartUps"
              line="MaxStartUps 50:100:200"
              state=present
  notify: Restart ssh

- name: Disallow password authentication
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PasswordAuthentication"
              line="PasswordAuthentication no"
              state=present
  notify: Restart ssh

- name: Disallow root SSH access
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PermitRootLogin"
              line="PermitRootLogin no"
              state=present
  notify: Restart ssh

- name: Create / delete users
  user: name={{ item.key }} comment="{{ item.value.name }}" state={{ item.value.state }} remove=yes
  with_dict: adminusers

- name: Set authorized keys for individual users
  authorized_key: user={{ item.key }} key="{{ lookup('file', '../files/public_keys/' + item.key + '.pub') }}" state={{ item.value.state }} exclusive=yes
  with_dict: adminusers
  when: item.value.state == 'present'

- name: Add configured user accounts to passwordless sudoers
  lineinfile:
    dest: /etc/sudoers
    regexp: '^{{ item.key }}'
    line: '{{ item.key }} ALL=(ALL) NOPASSWD: ALL'
    state: '{{ item.value.state }}'
    validate: 'visudo -cf %s'
  with_dict: adminusers

- name: Remove previous gw machine IP mappings from /etc/hosts
  lineinfile: dest=/etc/hosts regexp='^[0-9\.]* {{ item }}$' state=absent owner=root group=root mode=0644
  with_items: groups.va_loadbalancer

- name: Add gateway machine IP mappings to /etc/hosts
  lineinfile: dest=/etc/hosts line='{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}' owner=root group=root mode=0644
  with_items: groups.va_loadbalancer

- name: Remove previous build machine IP mapping from /etc/hosts
  lineinfile: dest=/etc/hosts regexp='^[0-9\.]* {{ item }}$' state=absent owner=root group=root mode=0644
  with_items: groups.va_build

- name: Add build machine IP mapping to /etc/hosts
  lineinfile: dest=/etc/hosts line='{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}' owner=root group=root mode=0644
  with_items: groups.va_build

- name: Remove previous app server IP mapping from /etc/hosts
  lineinfile: dest=/etc/hosts regexp='^[0-9\.]* {{ item }}$' state=absent owner=root group=root mode=0644
  with_items: groups.va_app

- name: Add app servers IP mapping to /etc/hosts
  lineinfile: dest=/etc/hosts line='{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}' owner=root group=root mode=0644
  with_items: groups.va_app
