- name: Set ssh MaxStartUps
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^MaxStartUps"
              line="MaxStartUps 50:100:200"
              state=present
  notify: Restart ssh

- name: Disallow password authentication
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PasswordAuthentication"
              line="PasswordAuthentication no"
              state=present
  notify: Restart ssh

- name: Disallow root SSH access
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PermitRootLogin"
              line="PermitRootLogin no"
              state=present
  notify: Restart ssh

- name: Create / delete users
  user: name={{ item.key }} comment="{{ item.value.name }}" state={{ item.value.state }} remove=yes force=yes
  with_dict: "{{ adminusers }}"

- name: Set authorized keys for individual users
  authorized_key: user={{ item.key }} key="{{ lookup('file', '../files/public_keys/' + item.key + '.pub') }}" state={{ item.value.state }} exclusive=yes
  with_dict: "{{ adminusers }}"
  when: item.value.state == 'present'

- name: Add configured user accounts to passwordless sudoers
  lineinfile:
    dest: /etc/sudoers
    regexp: '^{{ item.key }}'
    line: '{{ item.key }} ALL=(ALL) NOPASSWD: ALL'
    state: '{{ item.value.state }}'
    validate: 'visudo -cf %s'
  with_dict: "{{ adminusers }}"
  when: item.value.state == 'present'

- name: Add servers' IP mapping to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^[0-9\.]* {{ item.hostname }}$'
    line: '{{ item.address }} {{ item.hostname }}'
    owner: root
    group: root
    mode: 0644
  with_items:
    - hostname: oph-va-lb-prod01.csc.fi
      address: 86.50.28.144
    - hostname: oph-va-ci-test01.csc.fi
      address: 86.50.28.148
    - hostname: oph-va-app-test01.csc.fi
      address: 86.50.28.142
    - hostname: oph-va-app-prod01.csc.fi
      address: 86.50.28.143
