name: Deploy to environment
on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Deploy to ${{ inputs.env }}
    runs-on: ubuntu-22.04
    environment: ${{ inputs.env }}
    env:
      AWS_ACCOUNT_ID_DEV: ${{ secrets.AWS_ACCOUNT_ID_DEV }}
      AWS_ACCOUNT_ID_QA: ${{ secrets.AWS_ACCOUNT_ID_QA }}
      AWS_ACCOUNT_ID_PROD: ${{ secrets.AWS_ACCOUNT_ID_PROD }}
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Check commit deployment status
        run: ./deploy-scripts/check-commit-to-deploy-${{ inputs.env }}.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.DEPLOY_ROLE_ARN }}

      - name: 04-deploy-cdk.sh
        id: deploy
        run: ./deploy-scripts/04-deploy-cdk-${{ inputs.env }}.sh

      - name: set now timestamp
        id: now
        run: echo "timestamp=$(date -Iseconds | sed s/:/_/g )" >> $GITHUB_OUTPUT

      - name: Update green tag
        if: steps.deploy.outcome == 'success'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag --force va-green-${{ inputs.env }}
          git push --force origin va-green-${{ inputs.env }}
          git tag va-green-${{ inputs.env }}-${{ steps.now.outputs.timestamp }}
          git push origin va-green-${{ inputs.env }}-${{ steps.now.outputs.timestamp }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
