name: Build and test master
on:
  push:
    branches:
      - master

jobs:
  build:
    uses: ./.github/workflows/_build.yaml
    secrets: inherit

  deploy:
    needs: build
    uses: ./.github/workflows/_deploy-all.yaml
    secrets: inherit
