name: Build and test master
on:
  push:
    branches:
      - master

jobs:
  lint:
    uses: ./.github/workflows/_lint.yaml

  build:
    needs: lint
    uses: ./.github/workflows/_build.yaml
    secrets: inherit

  deploy:
    needs: build
    uses: ./.github/workflows/_deploy-all.yaml
    secrets: inherit
