name: Deploy prod
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency: deploy-prod

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
    with:
      env: prod
