name: Deploy dev
on:
  workflow_dispatch:
  push:
    branches:
      - green-master

defaults:
  run:
    shell: bash

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
    with:
      env: dev
  trigger-qa-deploy:
    name: Trigger QA deploy
    runs-on: ubuntu-22.04
    needs: deploy
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Run QA deploy workflow
        run: gh workflow run deploy-qa.yaml --ref va-green-dev
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
