name: Deploy
on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

concurrency: deploy-master

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit

  deploy-jars:
    name: 04-deploy-jars.sh
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/checkout@v4.0.0
      - name: Run 04-deploy-jars.sh
        run: ./deploy-scripts/04-deploy-jars.sh
