name: Deploy QA
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency: deploy-qa

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
    with:
      env: qa
