name: Deploy
on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true

defaults:
  run:
    shell: bash

concurrency: deploy-${{ inputs.env }}

jobs:
  deploy:
    name: Deploy to ${{ inputs.env }}
    runs-on: ubuntu-22.04
    environment: ${{ inputs.env }}
    env:
      AWS_ACCOUNT_ID_DEV: ${{ secrets.AWS_ACCOUNT_ID_DEV }}
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.DEPLOY_ROLE_ARN }}

      - name: 04-deploy-cdk.sh
        run: |
          aws sts get-caller-identity
          echo "$AWS_ACCOUNT_ID_DEV" | cut -c -3
