name: Lein dependency check
on:
  push:
    branches:
      - master
jobs:
  lein-dependency-check:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Configure java version
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4
        with:
          distribution: 'temurin'
          java-version: '8'
          check-latest: true

      - name: Run lein dependency check
        run: scripts/run_lein_dependency_check.sh
        env:
          NVD_API_TOKEN: ${{ secrets.NVD_API_TOKEN }}

      - name: Upload lein dependency check report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4
        with:
          name: lein_dependency_check_report
          path: dependency-check/target/nvd/valtionavustus/dependency-check-report.html
