name: Lein dependency check
on:
  push:
    branches:
      - master
jobs:
  lein-dependency-check:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Configure java version
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4
        with:
          distribution: 'temurin'
          java-version: '8'
          check-latest: true

      - name: Run lein dependency check
        run: scripts/run_lein_dependency_check.sh
        env:
          NVD_API_TOKEN: ${{ secrets.NVD_API_TOKEN }}

      - name: Upload lein dependency check report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@604373da6381bf24206979c74d06a550515601b9 # v4
        with:
          name: lein_dependency_check_report
          path: dependency-check/target/nvd/valtionavustus/dependency-check-report.html
