name: Lein dependency check
on:
  push:
    branches:
      - master
jobs:
  lein-depdency-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Configure java version
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          check-latest: true

      - name: Run lein dependency check
        run: scripts/run_lein_dependency_check.sh

      - name: Upload lein dependency check report
        uses: actions/upload-artifact@v4
        with:
          name: lein_dependency_check_report
          path: dependency-check/target/nvd/valtionavustus/dependency-check-report.html
