name: Renovate
on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '0 16/2,0-6/2 * * *'

concurrency: renovate

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/app-token-exporter
        id: app-token
        with:
          private_key: ${{ secrets.PRIVATE_KEY }}
          app_id: ${{ secrets.APP_ID }}
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@e3a862510f27d57a380efb11f0b52ad7e8dbf213 # v41.0.6
        with:
          configurationFile: .github/renovate.json
          token: ${{ steps.app-token.outputs.token }}
        env:
          LOG_LEVEL: 'debug'
