name: Renovate
on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '0 16/2,0-6/2 * * *'

concurrency: renovate

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: ./.github/actions/app-token-exporter
        id: app-token
        with:
          private_key: ${{ secrets.PRIVATE_KEY }}
          app_id: ${{ secrets.APP_ID }}
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@a1ed1d0adddfdf138192d1fbe3150a80094dee6a # v40.3.1
        with:
          configurationFile: .github/renovate.json
          token: ${{ steps.app-token.outputs.token }}
        env:
          LOG_LEVEL: 'debug'
