name: Renovate
on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '0 16/2,0-6/2 * * *'

concurrency: renovate

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: ./.github/actions/app-token-exporter
        id: app-token
        with:
          private_key: ${{ secrets.PRIVATE_KEY }}
          app_id: ${{ secrets.APP_ID }}
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@b266b24b144602ed4f512f0773009d026722f4cc # v40.2.6
        with:
          configurationFile: .github/renovate.json
          token: ${{ steps.app-token.outputs.token }}
        env:
          LOG_LEVEL: 'debug'
