name: Renovate
on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */2 * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - uses: ./.github/actions/app-token-exporter
        id: app-token
        with:
          private_key: ${{ secrets.PRIVATE_KEY }}
          app_id: ${{ secrets.APP_ID }}
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v36.0.2
        with:
          configurationFile: .github/renovate.json
          token: ${{ steps.app-token.outputs.token }}
          useSlim: false
        env:
          LOG_LEVEL: 'debug'
