name: Run tests on pr
on:
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Run test-on-pr.sh
        shell: bash
        run: ./test-on-pr.sh
        env:
          PLAYWRIGHT_WORKERS: 1 # GH Actions will choke to death with more workers

      - name: Upload Playwright results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-results
          path: playwright-results/
