name: Run tests on pr
on:
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Run test-on-pr.sh
        shell: bash
        run: ./test-on-pr.sh
