name: Run tests on pr
on:
  pull_request:
  merge_group:

jobs:
  lint:
    uses: ./.github/workflows/_lint.yaml
  build:
    needs: lint
    uses: ./.github/workflows/_build.yaml
    secrets: inherit
