- name: Install Docker apt repo key (Debian)
  apt_key: keyserver=pgp.mit.edu id=36A1D7869245C8950F966E92D8576A8BA88D21E9
  when: ansible_os_family == 'Debian'

- name: Add Docker apt repository (Debian)
  apt_repository: repo='deb https://get.docker.com/ubuntu docker main' state=present
  when: ansible_os_family == 'Debian'

- name: Install Docker (Debian)
  apt: state=installed pkg=lxc-docker force=yes
  when: ansible_os_family == 'Debian'

- name: Install Docker (RedHat)
  yum: state=installed pkg=lxc-docker
  when: ansible_os_family == 'RedHat'

- name: Install docker-compose (RedHat)
  yum: state=installed pkg=docker-compose
  when: ansible_os_family == 'RedHat'

- name: Allow Docker to create iptables rules dynamically
  lineinfile:
    dest: /etc/sysconfig/docker
    regexp: '^OPTIONS='
    line: "OPTIONS='--selinux-enabled -g /data/jenkins/docker --iptables=true'"

- name: Create docker group
  group: name=docker state=present

- name: Add "{{ jenkins_user }}" user to docker group
  user: name="{{ jenkins_user }}" groups=docker

- name: Ensure that docker daemon is started
  service: name=docker state=started enabled=yes

- name: Add directory for database db dumps storage
  file: path={{ database_dumps_dir }} owner={{ jenkins_user }} state=directory mode=0700

- name: Install g++ for jest (Debian)
  apt: state=installed pkg=g++
  when: ansible_os_family == 'Debian'

- name: Install g++ for jest (RedHat)
  yum:  state=installed pkg=gcc-c++
  when: ansible_os_family == 'RedHat'

- name: Add gitconfig
  copy:
    dest: /home/jenkins/.gitconfig
    content: "{{ lookup('file', 'gitconfig') }}"

- name: Ensure secrets directory exists
  file: path=/home/jenkins/secrets state=directory owner=jenkins group=jenkins

- name: Copy secrets to Jenkins
  copy:
    dest: /home/jenkins/secrets/secret-dev.edn
    src: ../../valtionavustus-secret/config/secret-dev.edn
    owner: jenkins
    group: jenkins
    mode: 0600
