- name: Install Docker apt repo key
  apt_key: keyserver=pgp.mit.edu id=36A1D7869245C8950F966E92D8576A8BA88D21E9

- name: Add Docker apt repository
  apt_repository: repo='deb https://get.docker.com/ubuntu docker main' state=present

- name: Install Docker
  apt: state=installed pkg=lxc-docker force=yes

- name: Add "{{ jenkins_user }}" user to docker group
  user: name="{{ jenkins_user }}" groups=docker

- name: Install g++ for jest
  apt: state=installed pkg=g++
